name: CI

on:
  push:
    branches: [ "25-unit-test-solve-yaml-problems" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Qt 6.5.0
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.5.0'
          host: 'linux'
          modules: 'qtbase'

      - name: Install Additional Dependencies for Qt xcb Plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb-xinerama0 libxcb-xinput0 libxkbcommon-x11-0 libxcb-xfixes0-dev \
                                  libxcb-util1 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 \
                                  libxcb-render-util0 libxcb-randr0 libxcb-xkb1 libxkbcommon-dev \
                                  libx11-xcb1 xvfb
      - name: Set Permissions for Qt Plugin Directory
        run: |
          sudo chmod -R 755 /home/runner/work/Team02-Module03/Qt/6.5.0/gcc_64/plugins
          sudo chmod -R 755 /home/runner/work/Team02-Module03/Qt/6.5.0/gcc_64/lib

      - name: Start Xvfb (Virtual Display)
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x16 &
        shell: bash

      - name: Verify Qt Installation
        run: |
          echo "Verifying Qt Installation at /home/runner/work/Team02-Module03/Qt"
          ls -R /home/runner/work/Team02-Module03/Qt

      - name: Compile the project with CMake
        run: |
          cd ex00
          mkdir -p build
          cd build
          cmake -DCMAKE_PREFIX_PATH=/home/runner/work/Team02-Module03/Qt/6.5.0/gcc_64 ..
          cmake --build .
        shell: bash
        continue-on-error: false

      - name: List Build Output Files
        run: |
          echo "Listing build directory contents for diagnostics:"
          ls -la ex00/build

      - name: Set Execute Permission for Test Executables
        run: |
          chmod +x ex00/build/*
          echo "Permissions set for test executables in ex00/build/"

      - name: Run Unit Logic Tests
        run: |
          cd ex00/build/
          echo "Running unit logic tests"
          ./run_tests || { echo "Logic tests failed"; exit 1; }
        shell: bash
        continue-on-error: false

      - name: Run Unit UI Tests
        env:
          DISPLAY: ":99"
          QT_DEBUG_PLUGINS: "1"  # Enable detailed plugin debug logging
        run: |
          cd ex00/build/
          echo "Running unit UI tests with detailed plugin logging"
          ./run_ui_tests || { echo "UI tests failed"; exit 1; }
        shell: bash
